// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NotionFlow.Api.Data;

#nullable disable

namespace NotionFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430000001_AddActivityPercentageValue")]
    partial class AddActivityPercentageValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a partial migration - the full snapshot is in AppDbContextModelSnapshot
        }
    }
}
